# Generated by Django 2.2.1 on 2019-05-20 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ejudge_users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ejudge_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjudgeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejudge_password', models.CharField(blank=True, max_length=255, verbose_name='Пароль в системе Ejudge')),
                ('ejudge_pwdmethod', models.CharField(choices=[('0', 'Plain'), ('1', 'Base 64'), ('2', 'SHA-1')], max_length=2, verbose_name='Тип шифрования')),
                ('ejudge_user', ejudge_users.models.EjudgeForeginKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejudge_models.Logins', verbose_name='Пользователь в системе Ejudge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Связанный пользователь')),
            ],
            options={
                'verbose_name_plural': 'Профили Ejudge',
                'verbose_name': 'Профиль Ejudge',
            },
        ),
    ]
