# Generated by Django 2.2.1 on 2019-06-14 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0003_auto_20190613_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('ejudge_id', models.CharField(max_length=10, unique=True, verbose_name='ID в системе Ejudge')),
                ('scope_system', models.CharField(blank=True, choices=[('acm', 'ACM')], max_length=10, verbose_name='Тип контеста')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Дата начала')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность в минутах')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрытый контест')),
                ('secret_word', models.CharField(blank=True, max_length=40, verbose_name='Кодовое слово')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('problems', models.ManyToManyField(to='problems.Problems', verbose_name='Список задач')),
            ],
            options={
                'verbose_name': 'Контест',
                'verbose_name_plural': 'Контесты',
                'db_table': 'contests',
            },
        ),
    ]
