# Generated by Django 2.2.1 on 2019-06-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Доступен в списке'),
        ),
    ]
